<?xml version="1.0" encoding="utf-8"?><workItemType dslVersion="12.0.0.0" Name="Solicitud de servicio" source="D:\Adopción_TeamFoundation\OpendatProcess V5.0\WorkItem Tracking\TypeDefinitions\ServiceRequest.xml" xmlns="http://schemas.microsoft.com/dsltools/WITDesigner" />